
'name': 'Vaishnavi Jadhav', 
'gender': 'Female',
'dot': '2021-06-08', 
'dob': '2021-06-17', 
'age': 0, 
'informant': 'Father',
'class': 'I', 
'2_age_observation': 'appropriate', 
'2_attention': 'could be', 
'appropriateness': 'appropriateness', 
'inappropriate ': 'inappropriate ', 
'inappropriateness ': 'inappropriateness ',
'schonell_list_0': 'adequate',
'schonell_list_1': 'adequate',
'schonell_list_2': 'adequate',
'schonell_list_3': 'could be', 
'schonell_list_4': 'appropriate', 
'schonell_list_5': 'could', 
'auditory_res': 'inappropriate', 
'2_referral': 'Department of\n          Special Education (DSE)of his school', 
'school': 'St. Andrews School, Keesara,\n          Hyderabad, Telangana', 
'complaints': 'fear of exams, low academic performance and selective social interaction. He has been\n          availing remedial support from DSE of his school.', 
'languages': 'Telugu & Hindi', 
'2_qualities': 'well oriented and was\n          motivated', 
'2_response': 'slow and needed more time', 
'final_review': 'There is a discrepancy of above 24 points\n        between the two scale scores, suggestive of presence of learning difficulty. He might exhibit difficulties in\n        the\n        areas of, visual discrimination, attention to visual detail, abstract visual-perceptual ability, spatial and\n        nonverbal problem-solving, visual analysis and construction of a whole from its parts and mental planning\n        skills', 
'final_percentile': 'below 25th', 
'final_intelligence': 'low average', 
'schonell_reading_handwriting': 'handwriting shows', 
'schonell_reading_age': '12 years 6 months\n      ',
'schonell_spelling_age': '7\n        years 5 months', 
'schonell_summary': 'severe level of inadequacy', 
'schonell_list_7': 'however tries to\n read letter by letter, hence takes more time\n            for reading', 
'auditory_age': '8 years 6\n        months',
'auditory_summary': 'appropriate', 
'auditory_report': 'However, he makes mistakes in graded sums of multiplication, division and fractions.\n        He makes visuospatial and procedural errors in calculations', 
'final_summary': 'with learning expression mostly as inappropriate\n        language processing and expression and\n        significant difficulty in visuo perception and processing. The profile and the observation data match with\n        profile\n        of Slow learner.', 
'tests': [True, True, True, True, True, True], 
'sattler_table': [[False, True, False, False, False], [False, False, True, False, False], [False, False, False, True, False], [False, False, False, False, True], [False, False, False, True, False], [False, False, True, False, False], [False, True, False, False, False]],
'year': 0, 
'month': 0,
'ravens_test': 'Colour',
'verbal_tests_average': 100, 
'verbal_tests': ['100', '100', '100', '100', '100'], 
'full_score': 50, 
'performance_tests_average': 100, 
'performance_tests': ['100', '100', '100', '100', '100']}

print(type(a['dot']))