# Generated by Django 2.0.7 on 2021-06-20 08:37

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=100, null=True)),
                ('i_gender', models.CharField(max_length=100, null=True)),
                ('i_dot', models.DateField(null=True)),
                ('i_dob', models.DateField(null=True)),
                ('i_age', models.IntegerField(null=True)),
                ('i_informant', models.CharField(max_length=100, null=True)),
                ('i_class', models.CharField(max_length=10, null=True)),
                ('i_2_age_observation', models.CharField(max_length=100, null=True)),
                ('i_2_attention', models.CharField(max_length=100, null=True)),
                ('i_appropriateness', models.CharField(max_length=100, null=True)),
                ('i_inappropriate', models.CharField(max_length=100, null=True)),
                ('i_inappropriateness', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_0', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_1', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_2', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_3', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_4', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_5', models.CharField(max_length=100, null=True)),
                ('i_auditory_res', models.CharField(max_length=100, null=True)),
                ('i_report_name', models.CharField(max_length=100, null=True)),
                ('i_2_referral', models.CharField(max_length=100, null=True)),
                ('i_school', models.CharField(max_length=100, null=True)),
                ('i_complaints', models.CharField(max_length=100, null=True)),
                ('i_languages', models.CharField(max_length=100, null=True)),
                ('i_2_qualities', models.CharField(max_length=100, null=True)),
                ('i_2_response', models.CharField(max_length=100, null=True)),
                ('i_final_review', models.CharField(max_length=100, null=True)),
                ('i_final_percentile', models.CharField(max_length=100, null=True)),
                ('i_final_intelligence', models.CharField(max_length=100, null=True)),
                ('i_schonell_reading_handwriting', models.CharField(max_length=100, null=True)),
                ('i_schonell_reading_age', models.CharField(max_length=100, null=True)),
                ('i_schonell_spelling_age', models.CharField(max_length=100, null=True)),
                ('i_schonell_summary', models.CharField(max_length=100, null=True)),
                ('i_schonell_list_7', models.CharField(max_length=100, null=True)),
                ('i_auditory_age', models.CharField(max_length=100, null=True)),
                ('i_auditory_summary', models.CharField(max_length=100, null=True)),
                ('i_auditory_report', models.CharField(max_length=100, null=True)),
                ('i_final_summary', models.CharField(max_length=100, null=True)),
                ('i_tests', models.CharField(max_length=100, null=True)),
                ('i_sattler_table', models.CharField(max_length=100, null=True)),
                ('i_year', models.IntegerField(null=True)),
                ('i_month', models.IntegerField(null=True)),
                ('i_ravens_test', models.CharField(max_length=100, null=True)),
                ('i_verbal_tests_average', models.IntegerField(null=True)),
                ('i_verbal_tests', models.CharField(max_length=100, null=True)),
                ('i_full_score', models.IntegerField(null=True)),
                ('i_performance_tests_average', models.IntegerField(null=True)),
                ('i_performance_tests', models.CharField(max_length=100, null=True)),
                ('report', models.FileField(upload_to='media')),
            ],
            options={
                'ordering': ('-patient_id',),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
