# Generated by Django 2.0.7 on 2021-06-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_patient',
            old_name='report',
            new_name='Report',
        ),
        migrations.AddField(
            model_name='report_patient',
            name='report_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report_patient',
            name='i_dob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report_patient',
            name='i_dot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
