# Generated by Django 2.2 on 2021-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210621_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_patient',
            name='ijkappropriate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_patient',
            name='ijkschonell_reading_handwriting_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_patient',
            name='ijkschonell_reading_handwriting_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_patient',
            name='ijkschonell_reading_handwriting_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_patient',
            name='ijksevere_level_of_inadequacy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
