# Generated by Django 2.2 on 2021-07-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210623_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_patient',
            name='ijkrecommendations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_patient',
            name='ijkrecommendations_input',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
