# Generated by Django 3.2 on 2021-07-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210702_1032'),
        ('Home', '0006_auto_20210702_1054'),
    ]

    operations = [
    ]
