# Generated by Django 3.2 on 2021-07-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_merge_0006_auto_20210702_1032_0006_auto_20210702_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_patient',
            name='ijkdigit_vocab',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
